// =============================================================================
// Mock Data — Used for frontend development before API keys are configured
// =============================================================================

import { Candidate } from '@/types/candidate';

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: '1', role_id: 'r1', name: 'Arjun Mehta', email: 'arjun.mehta@gmail.com', phone: '+919876543210',
    college: 'IIT Bombay', degree: 'B.Tech Computer Science', grad_year: '2023',
    experience_band: '0-2', linkedin_url: 'https://linkedin.com/in/arjunmehta', github_url: 'https://github.com/arjunmehta',
    resume_pdf_url: null, resume_text: 'Built production React apps...',
    github_summary: { username: 'arjunmehta', bio: 'Full-stack dev', public_repos: 34, account_age_days: 1200, top_repos: [], languages: [{ language: 'TypeScript', count: 15 }, { language: 'Python', count: 8 }], activity_score: 84, project_quality_score: 76, active_weeks_90d: 10, last_push_days_ago: 3 },
    domain_signals: ['React', 'Next.js', 'TypeScript', 'Tailwind'], primary_domain: 'frontend',
    llm_profile_summary: 'Strong frontend engineer with production React experience. Has built and shipped multiple Next.js applications with excellent TypeScript skills. Active GitHub contributor with consistent commit history.',
    fit_reasoning: 'Excellent domain alignment for frontend role. Strong React + Next.js experience directly matches requirements. IIT Bombay CS background provides strong fundamentals.',
    resume_context_score: 90, github_signal_score: 84, domain_alignment_score: 96,
    experience_score: 70, college_tier_score: 100, total_score: 89.6, rank: 1,
    shortlisted: true, email_approved: false, email_sent: false, created_at: '2026-05-01T10:00:00Z',
  },
  {
    id: '2', role_id: 'r1', name: 'Priya Sharma', email: 'priya.sharma@outlook.com', phone: '+919123456789',
    college: 'IIIT Hyderabad', degree: 'B.Tech CSE', grad_year: '2022',
    experience_band: '2-4', linkedin_url: 'https://linkedin.com/in/priyasharma', github_url: 'https://github.com/priyasharma',
    resume_pdf_url: null, resume_text: 'Led frontend team at startup...',
    github_summary: { username: 'priyasharma', bio: 'Frontend engineer', public_repos: 28, account_age_days: 1500, top_repos: [], languages: [{ language: 'JavaScript', count: 18 }, { language: 'TypeScript', count: 10 }], activity_score: 90, project_quality_score: 80, active_weeks_90d: 11, last_push_days_ago: 1 },
    domain_signals: ['React', 'Vue.js', 'CSS', 'Figma', 'Redux'], primary_domain: 'frontend',
    llm_profile_summary: 'Experienced frontend engineer who has led a small team. Strong design sensibility with Figma experience. Has worked across React and Vue ecosystems.',
    fit_reasoning: 'Strong fit — 2+ years of professional frontend experience with team lead exposure. Domain signals perfectly aligned. Very active on GitHub.',
    resume_context_score: 86, github_signal_score: 90, domain_alignment_score: 92,
    experience_score: 84, college_tier_score: 80, total_score: 87.8, rank: 2,
    shortlisted: true, email_approved: false, email_sent: false, created_at: '2026-05-01T10:05:00Z',
  },
  {
    id: '3', role_id: 'r1', name: 'Rahul Verma', email: 'rahul.v@yahoo.com', phone: '+918765432109',
    college: 'NIT Trichy', degree: 'B.Tech ECE', grad_year: '2021',
    experience_band: '2-4', linkedin_url: 'https://linkedin.com/in/rahulverma', github_url: 'https://github.com/rahulverma',
    resume_pdf_url: null, resume_text: 'Backend engineer with Django and Node.js...',
    github_summary: { username: 'rahulverma', bio: 'Backend dev', public_repos: 22, account_age_days: 1800, top_repos: [], languages: [{ language: 'Python', count: 14 }, { language: 'JavaScript', count: 6 }], activity_score: 70, project_quality_score: 64, active_weeks_90d: 7, last_push_days_ago: 15 },
    domain_signals: ['Django', 'Node.js', 'PostgreSQL', 'REST API'], primary_domain: 'backend',
    llm_profile_summary: 'Solid backend engineer with experience across Python and Node.js stacks. Has built REST APIs and worked with PostgreSQL databases.',
    fit_reasoning: 'Backend-focused profile — moderate alignment for frontend role. Has some JavaScript experience but lacks direct React/frontend framework exposure.',
    resume_context_score: 64, github_signal_score: 70, domain_alignment_score: 40,
    experience_score: 80, college_tier_score: 80, total_score: 61.6, rank: 5,
    shortlisted: true, email_approved: false, email_sent: false, created_at: '2026-05-01T10:10:00Z',
  },
  {
    id: '4', role_id: 'r1', name: 'Sneha Patel', email: 'sneha.p@gmail.com', phone: '+917654321098',
    college: 'DTU', degree: 'B.Tech IT', grad_year: '2024',
    experience_band: '0-2', linkedin_url: 'https://linkedin.com/in/snehapatel', github_url: 'https://github.com/snehapatel',
    resume_pdf_url: null, resume_text: 'Full stack developer with React and Express...',
    github_summary: { username: 'snehapatel', bio: 'Full stack', public_repos: 19, account_age_days: 900, top_repos: [], languages: [{ language: 'TypeScript', count: 10 }, { language: 'Python', count: 5 }], activity_score: 76, project_quality_score: 70, active_weeks_90d: 8, last_push_days_ago: 7 },
    domain_signals: ['React', 'Express', 'MongoDB', 'TypeScript', 'Tailwind'], primary_domain: 'fullstack',
    llm_profile_summary: 'Emerging full-stack developer with balanced frontend and backend skills. Solid React foundation with Express.js backend experience.',
    fit_reasoning: 'Good full-stack foundation with frontend leaning. React + TypeScript + Tailwind alignment is strong. Less depth than senior candidates but shows promise.',
    resume_context_score: 76, github_signal_score: 76, domain_alignment_score: 70,
    experience_score: 60, college_tier_score: 80, total_score: 73.0, rank: 3,
    shortlisted: true, email_approved: false, email_sent: false, created_at: '2026-05-01T10:15:00Z',
  },
  {
    id: '5', role_id: 'r1', name: 'Vikram Singh', email: 'vikram.s@proton.me', phone: '+916543210987',
    college: 'BITS Pilani', degree: 'B.E. Computer Science', grad_year: '2020',
    experience_band: '4+', linkedin_url: 'https://linkedin.com/in/vikramsingh', github_url: 'https://github.com/vikramsingh',
    resume_pdf_url: null, resume_text: 'Senior frontend architect at fintech...',
    github_summary: { username: 'vikramsingh', bio: 'Senior FE architect', public_repos: 45, account_age_days: 2500, top_repos: [], languages: [{ language: 'TypeScript', count: 25 }, { language: 'JavaScript', count: 12 }], activity_score: 60, project_quality_score: 90, active_weeks_90d: 5, last_push_days_ago: 25 },
    domain_signals: ['React', 'Next.js', 'TypeScript', 'Design System', 'Webpack'], primary_domain: 'frontend',
    llm_profile_summary: 'Senior frontend architect with 4+ years at a fintech. Has designed and built component libraries and design systems. Deep TypeScript expertise.',
    fit_reasoning: 'Highly experienced frontend specialist. Overqualified for SDE-1 role but exceptional domain alignment. GitHub shows strong project quality despite lower recent activity.',
    resume_context_score: 94, github_signal_score: 60, domain_alignment_score: 98,
    experience_score: 96, college_tier_score: 80, total_score: 86.6, rank: 4,
    shortlisted: true, email_approved: false, email_sent: false, created_at: '2026-05-01T10:20:00Z',
  },
  {
    id: '6', role_id: 'r1', name: 'Ananya Iyer', email: 'ananya.i@gmail.com', phone: '+915432109876',
    college: 'VIT Vellore', degree: 'B.Tech CSE', grad_year: '2023',
    experience_band: '0-2', linkedin_url: 'https://linkedin.com/in/ananyaiyer', github_url: 'https://github.com/ananyaiyer',
    resume_pdf_url: null, resume_text: 'ML engineer with PyTorch and NLP projects...',
    github_summary: { username: 'ananyaiyer', bio: 'ML enthusiast', public_repos: 15, account_age_days: 1000, top_repos: [], languages: [{ language: 'Python', count: 12 }, { language: 'Jupyter Notebook', count: 5 }], activity_score: 56, project_quality_score: 60, active_weeks_90d: 4, last_push_days_ago: 30 },
    domain_signals: ['PyTorch', 'NLP', 'Transformers', 'Python'], primary_domain: 'ml-ai',
    llm_profile_summary: 'ML-focused engineer with strong NLP and PyTorch experience. Has several Kaggle competitions and published research-adjacent projects.',
    fit_reasoning: 'ML/AI specialist — poor alignment for frontend role. No frontend framework experience detected. Strong in a different domain.',
    resume_context_score: 70, github_signal_score: 56, domain_alignment_score: 24,
    experience_score: 60, college_tier_score: 80, total_score: 55.2, rank: 6,
    shortlisted: true, email_approved: false, email_sent: false, created_at: '2026-05-01T10:25:00Z',
  },
];
